# KapwaNet - Community Platform for Dignified Mutual Aid
# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.9 on 2025-12-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.CharField(help_text="Unique identifier for the preset (e.g., 'default', 'sunset')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the preset', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of the theme's look and feel")),
                ('theme_json', models.JSONField(default=dict, help_text='Complete theme configuration as JSON')),
                ('preview_colors', models.JSONField(default=list, help_text='List of 3-4 preview colors for the theme selector')),
                ('is_dark', models.BooleanField(default=False, help_text='Whether this is a dark mode theme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'theme preset',
                'verbose_name_plural': 'theme presets',
                'db_table': 'theme_presets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgTheme',
            fields=[
                ('org', models.OneToOneField(help_text='The organization this theme belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='theme', serialize=False, to='organizations.organization')),
                ('theme_json', models.JSONField(default=dict, help_text='Theme configuration with colors, fonts, radius, spacing')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preset', models.ForeignKey(blank=True, help_text='The preset this theme is based on (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organizations.themepreset')),
            ],
            options={
                'verbose_name': 'organization theme',
                'verbose_name_plural': 'organization themes',
                'db_table': 'org_themes',
            },
        ),
    ]
