# Generated by Django 5.2.9 on 2025-12-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_themepreset_orgtheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateLibrary',
            fields=[
                ('id', models.CharField(help_text="Unique identifier for the template (e.g., 'home-starter')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the template', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this template is for')),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('programs', 'Programs Page'), ('contact', 'Contact Page'), ('custom', 'Custom Page')], default='custom', help_text='The type of page this template creates', max_length=20)),
                ('category', models.CharField(choices=[('starter', 'Starter Templates'), ('community', 'Community Organization'), ('nonprofit', 'Nonprofit / Charity'), ('mutual_aid', 'Mutual Aid Group')], default='starter', help_text='Category for organizing templates', max_length=30)),
                ('blocks_json', models.JSONField(default=list, help_text='Array of block configurations for this template')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Preview thumbnail image URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_preset', models.ForeignKey(blank=True, help_text='Recommended theme preset for this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='organizations.themepreset')),
            ],
            options={
                'verbose_name': 'page template',
                'verbose_name_plural': 'page templates',
                'db_table': 'template_library',
                'ordering': ['category', 'page_type', 'name'],
            },
        ),
    ]
