# Generated by Django 5.2.9 on 2025-12-28 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_template_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the page', primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (unique per org)', max_length=100)),
                ('title', models.CharField(help_text='Page title', max_length=255)),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('programs', 'Programs Page'), ('contact', 'Contact Page'), ('custom', 'Custom Page')], default='custom', help_text='The type of page', max_length=20)),
                ('blocks_json', models.JSONField(default=list, help_text='Array of block configurations for this page')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status of the page', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(help_text='The organization this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='organizations.organization')),
                ('source_template', models.ForeignKey(blank=True, help_text='The template this page was created from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_pages', to='organizations.templatelibrary')),
            ],
            options={
                'verbose_name': 'organization page',
                'verbose_name_plural': 'organization pages',
                'db_table': 'org_pages',
                'ordering': ['org', 'title'],
                'unique_together': {('org', 'slug')},
            },
        ),
    ]
